# Paths
db_file            "~/.local/share/mpd/database"
log_file           "~/.cache/mpd/log"
playlist_directory "~/.config/mpd/playlists"
state_file         "~/.config/mpd/state"

# Connection (This is likely why rmpc fails)
bind_to_address    "127.0.0.1"
port               "6600"

# Optional: Also bind to a physical socket file
bind_to_address    "~/.config/mpd/socket"
